#!/usr/bin/env python
"""
Full Pipeline — Runs all 10 days sequentially.
Every number in every table is generated by this pipeline.
No manual copying from interactive sessions.
"""
import sys
import os
import time
import subprocess
import traceback

SCRIPTS_DIR = os.path.dirname(os.path.abspath(__file__))


def run_day(day_num, script_name):
    """Run a single day's script as subprocess."""
    print(f"\n{'#' * 70}")
    print(f"# DAY {day_num}")
    print(f"{'#' * 70}\n")

    script_path = os.path.join(SCRIPTS_DIR, script_name)
    start = time.time()

    try:
        result = subprocess.run(
            [sys.executable, script_path],
            cwd=os.path.dirname(SCRIPTS_DIR),
            timeout=300,
            capture_output=False,
            env={**os.environ, "PYTHONIOENCODING": "utf-8"}
        )
        elapsed = time.time() - start
        success = result.returncode == 0
        status = "OK" if success else f"FAILED (exit code {result.returncode})"
        print(f"\n[DAY {day_num}] {status} in {elapsed:.1f}s")
        return success
    except subprocess.TimeoutExpired:
        elapsed = time.time() - start
        print(f"\n[DAY {day_num}] TIMEOUT after {elapsed:.1f}s")
        return False
    except Exception as e:
        elapsed = time.time() - start
        print(f"\n[DAY {day_num}] FAILED after {elapsed:.1f}s: {e}")
        traceback.print_exc()
        return False


def main():
    print("=" * 70)
    print(" FULL PIPELINE — Single-Image Visual Geolocation")
    print(" Every number is generated by this pipeline.")
    print(" No manual copying allowed.")
    print("=" * 70)

    days = [
        (1, "day1_setup_eval.py"),
        (2, "day2_geoclip_baseline.py"),
        (3, "day3_streetclip_zs.py"),
        (4, "day4_faiss_knn.py"),
        (5, "day5_cell_classifier.py"),
        (6, "day6_hybrid_v1.py"),
        (7, "day7_landmarks_ocr.py"),
        (8, "day8_full_eval.py"),
        (9, "day9_visualizations.py"),
        (10, "day10_report.py"),
    ]

    total_start = time.time()
    results = {}

    for day_num, script in days:
        success = run_day(day_num, script)
        results[day_num] = {"script": script, "success": success}

    total_elapsed = time.time() - total_start

    print("\n" + "=" * 70)
    print(" PIPELINE SUMMARY")
    print("=" * 70)
    for day_num, info in results.items():
        status = "OK" if info["success"] else "FAILED"
        print(f"  Day {day_num:2d}: {info['script']:<35s} [{status}]")
    print(f"\n  Total time: {total_elapsed:.1f}s")
    print("=" * 70)


if __name__ == "__main__":
    main()
